### ISSUE TITLE
Planning the rails app

### ISSUE THREAD

**Issue by amite** [contentstack/contentstack-ruby#2]
1. Shall we build an ecommerce app that looks like this? https://codepen.io/rohan10/pen/kEqno

2. I have created a contentstack but have no idea if I have structured it correctly. Need your review and input

This is what my stacks look like:

<img width="1153" alt="screenshot 2016-12-26 19 55 15" src="https://cloud.githubusercontent.com/assets/1308947/21483277/5aeaf674-cba5-11e6-8131-01f8debff39d.png">

Is this correct?

**Comment by mayankmishra** [comment]
Below is the structure -

**Product**
  Name/Title (text, singleline)
  Description (text, multiline)
  Featured Images (file, image, multiple)
  Price (number)
  Offer Price (number)
  Categories (reference, category, multiple)
  Sizes (reference, size, multiple)
  Brands (reference, brand) 
  In Stock? (boolean)
  Related Products (reference, self, multiple)
  
**Size**
  Name/Title (text, singleline)
  Description (text, multiline)
 
**Brand**
  Title (text, singleline)
  Logo (file, image)
  Description (text, multiline)
  
**Category**
  Title (text, singleline)
  Image (file, image)
  Description (text, multiline)
