### ISSUE TITLE
Change in api: fetch all resources by content_type first

### ISSUE THREAD

**Issue by amite** [contentstack/contentstack-ruby#7]
@mayankmishra lets write the full api for assets, content types and entries as well

**Comment by amite** [comment]
## Querying Entries

Get all Entries
```
blog_entries = stack.content_type('blog').get
```

Get all Entries with params
```
blog_entries = stack.content_type('blog').get({params: someParams}, {query: queryParams})
```

## Creating new Entries
```
blog_entries = stack.content_type('blog').create({ params: validParams })
```

## Updating Entries
`blog_entries = stack.content_type('blog').entry('blt1234567890abcef').update({ params: someParams })`

## Deleting Entries
```
blog_entries = stack.content_type('blog').get({params: someParams}, {query: queryParams}).delete
```

**Comment by amite** [comment]
@mayankmishra lets write the full api for assets, content types and entries as well

**Comment by uttamukkoji** [comment]
The above stated functionality are implemented in the SDK. Following are the details for the implementation

Fetching a single entry
`blog_entry =  client.content_type("blog").entry('entry_uid').fetch`

#### Querying a entries:
Get all Entries
`blog_entries = client.content_type("blog").query.fetch`

Get all Entries with params
`blog_entries = client.content_type("blog").query.where('author', 'John Doe').fetch`

> Create, Update, and Delete functionality is not supported in Content Delivery API's, so these functionality is not implemented in Delivery SDK. 

Closing this issue as all required functionality is exist in current version of SDK.
